export enum ErrorCode {
  NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  MAX_LOGIN_ATTEMPTS_CODE = 'MAX_LOGIN_ATTEMPTS_CODE',
  MAX_CODE_ATTEMPTS = 'MAX_CODE_ATTEMPTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_CONFIRMED = 'USER_NOT_CONFIRMED',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  INSUFFICIENT_PRIVILEGES = 'INSUFFICIENT_PRIVILEGES',
  INVALID_AUTH_TOKEN = 'INVALID_AUTH_TOKEN',
  INCORRECT_FORM_DATA = 'INCORRECT_FORM_DATA',
  INCORRECT_CODE = 'INCORRECT_CODE',
  EXPIRED_CODE = 'EXPIRED_CODE',
  AUTH_CODE_EXPIRED = 'AUTH_CODE_EXPIRED',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  RESOURCES_NOT_FOUND = 'RESOURCES_NOT_FOUND',
  DATA_CONFLICT = 'DATA_CONFLICT',
  OPERATION_CAN_NOT_BE_PERFORMED = 'OPERATION_CAN_NOT_BE_PERFORMED'

}
