module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/libs/authenticate',
    '<rootDir>/libs/custom-error',
    '<rootDir>/libs/jwt-helper',
    '<rootDir>/libs/schemas',
    '<rootDir>/libs/logger',
    '<rootDir>/libs/mailer',
    '<rootDir>/libs/validators',
    '<rootDir>/libs/sms-helper',
    '<rootDir>/apps/swagger',
    '<rootDir>/apps/fhir-extension',
    '<rootDir>/apps/socket-io',
    '<rootDir>/libs/controllers',
    '<rootDir>/libs/fhir-connector',
    '<rootDir>/libs/mongo-connect',
    '<rootDir>/libs/roles-map',
    '<rootDir>/libs/user-resource',
    '<rootDir>/tests',
    '<rootDir>/apps/auth',
    '<rootDir>/apps/bthub',
    '<rootDir>/libs/make-pdf',
    '<rootDir>/libs/i18next',
  ],
};
